---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mrdevops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mrdevops
  template:
    metadata:
      labels:
        app: mrdevops
    spec:
      containers:
      - name: mrdevops
        image: rohinisbag/project-cdac:v1.37
        imagePullPolicy: Always
        ports:
        - containerPort: 80
